### ISSUE TITLE
Changes to rotation should preserve unit quaternion

### ISSUE THREAD

**Issue by willcrichton** [jakobhellermann/bevy-inspector-egui#1]
When you use the UI to rotate an object, you can generate a non-unit quaternion which doesn't correctly describe a rotation. Ideally the UI would enforce this constraint.

https://github.com/jakobhellermann/bevy-inspector-egui/blob/main/src/impls/bevy_impls.rs#L27-L29

**Comment by jakobhellermann** [comment]
Thanks. It's fixed [now](https://github.com/jakobhellermann/bevy-inspector-egui/commit/48fce89f7692408bad4841b126f7e68d8995fffd#diff-5f751fbfe3e4b1f2bc256c8e152c020a118632c17cb46b4ce7c9162b5d365daa) but maybe in the future we could display a gizmo like [this](https://github.com/CedricGuillemet/ImGuizmo#ImGuizmo), although maybe that probably makes more sense to have in the world rather than UI and can live in another plugin.
