### ISSUE TITLE
Bevy 0.13

### ISSUE THREAD

**Issue by asour8** [jakobhellermann/bevy-inspector-egui#184]
Bevy 0.13
![image](https://github.com/jakobhellermann/bevy-inspector-egui/assets/52638772/5f0c5435-93b3-46d4-971b-08e191f1655e)

**Comment by tbillington** [comment]
`bevy-inspector-egui` will be blocked on `bevy_egui`.

You can follow the progress on bevy_egui upgrading to 0.13 https://github.com/mvlabat/bevy_egui/issues/259.

**Comment by BD103** [comment]
This may be completed in #185.

**Comment by RobWalt** [comment]
@asour8 I'm going to give you the benefit of a doubt and assume this was meant to be funny. Please consider that issue like these might put pressure on people who are working hard to provide software for free for others. They have an ordinary life too. If you're in need of such a change, please try to communicate more clearly why it is an issue and that it is urgently needed. And last but not least there's always the option of looking into the code yourself to do the necessary changes for things like an update.

**Comment by nablabla** [comment]
Hi, I don't know whats going on here, but since it is about migration to 0.13.0, I wanted to kindly report that the project does not compile for the WASM target as soon as you add the egui. There is a solution (i guess):
https://github.com/StarArawn/bevy_ecs_tilemap/issues/516#issuecomment-1958430867
```
error[E0599]: no method named `gpu` found for struct `Navigator` in the current scope
   --> C:\Users\Jan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.17.2\src\backend\web.rs:945:68
    |
945 |             global.unchecked_into::<web_sys::Window>().navigator().gpu()
    |                                                                    ^^^ method not found in `Navigator`
```

**Comment by asour8** [comment]
> @asour8 I'm going to give you the benefit of a doubt and assume this was meant to be funny. Please consider that issue like these might put pressure on people who are working hard to provide software for free for others. They have an ordinary life too. If you're in need of such a change, please try to communicate more clearly why it is an issue and that it is urgently needed. And last but not least there's always the option of looking into the code yourself to do the necessary changes for things like an update.

? this was just an issue to track bevy 0.13 support because a new release happened, i was just curious if the project was planning on upgrading to it or not

its fine tho i can close it then if it adds pressure, that wasnt my intent, sorry

**Comment by RobWalt** [comment]
Let me be clear: It's really nothing personal. I have to admit I was a bit angry while writing that but I wasn't angry at you. I just wished that tracking issues like these here are more constructive. We're talking over the internet here, so we need to be extra careful with each other since most things present in normal communication are not available (Facial expressions and gestures). So maybe you were just hyped for the next release which is also fair and I don't want to put you down with this. Next time please just consider using more words so we can understand your intents. This way we won't have to guess what you're actually trying to say which in the end lead to less drama overall.

Let me end this by saying again: I don't dislike you because of this. Thinking about it twice actually makes me think that you really just wanted to start something here. Sorry it went how it did.
