### ISSUE TITLE
Inspectable component not working with WorldInspectorPlugin

### ISSUE THREAD

**Issue by Sheepyhead** [jakobhellermann/bevy-inspector-egui#19]
Hi, I have a project where I simply add the WorldInspectorPlugin and everything worked smoothly until I had to inspect a component struct I'd made myself. I derived Inspectable for the struct (and for the custom types the struct contains all the way down until I hit primitives) and yet when I attempt to inspect it in the GUI, I still get "inspectable has not been defined for this component" despite the fact that the Inspectable trait *is* derived on the component struct and the code does compile and run. If nothing else, this seems like it shouldn't compile.

![image](https://user-images.githubusercontent.com/15895891/119727869-1a7f5100-be73-11eb-9b38-45a8e0e419b8.png)

![image](https://user-images.githubusercontent.com/15895891/119727883-1ce1ab00-be73-11eb-956e-245a730d9861.png)

**Comment by jakobhellermann** [comment]
If you want to use your own component with the world inspector, you also need to register it at the `InspectableRegistry` like this:
https://github.com/jakobhellermann/bevy-inspector-egui/blob/4dcfb246a4831505ca5b27f66abe8adad875a11f/examples/world.rs#L20-L25

This is neccessary because otherwise bevy has no way of knowing what traits a component implements.

**Comment by Sheepyhead** [comment]
That works, thanks!
